apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: yljf8drcl-python
  janus-idp.io/tekton: yljf8drcl-python
  backstage.io/kubernetes-id: yljf8drcl-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yljf8drcl-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
