apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: yljf8drcl-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yljf8drcl-python 
  name: yljf8drcl-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: yljf8drcl-python 
